language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install tox-travis
script:
  - tox -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
